# Generated by Django 3.2.12 on 2022-02-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20220208_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_logo',
            field=models.FileField(upload_to='images/', verbose_name='logo:'),
        ),
    ]
