# Generated by Django 3.2.9 on 2022-02-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_auto_20220211_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='status',
        ),
    ]
