# Generated by Django 3.2.9 on 2022-02-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_remove_candidate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(default=1, max_length=100, verbose_name='status:'),
            preserve_default=False,
        ),
    ]
