# Generated by Django 3.2.12 on 2022-02-17 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(max_length=100, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(max_length=100, verbose_name='status'),
        ),
    ]
