# Generated by Django 3.2.9 on 2022-02-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_auto_20220217_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='comapany_id',
            new_name='company_id',
        ),
    ]
