# Generated by Django 3.2.9 on 2022-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_rename_comapany_id_complaint_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_msg',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_reply',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_id',
            new_name='feedback_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_msg',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_reply',
            new_name='reply',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feed_sub',
            new_name='sub',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='complaint_sub',
        ),
        migrations.AddField(
            model_name='complaint',
            name='sub',
            field=models.CharField(default=1, max_length=200, verbose_name='subject'),
            preserve_default=False,
        ),
    ]
