# Generated by Django 3.2.9 on 2022-03-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_auto_20220225_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_status',
            new_name='status',
        ),
        migrations.AddField(
            model_name='job',
            name='job_cutoff',
            field=models.CharField(default=1, max_length=100, verbose_name='cut'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_examschedule',
            field=models.CharField(default=1, max_length=100, verbose_name='exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=1, max_length=100, verbose_name='answer'),
            preserve_default=False,
        ),
    ]
