# Generated by Django 3.2.9 on 2022-03-09 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_auto_20220303_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option5',
        ),
    ]
