# Generated by Django 3.2.9 on 2022-03-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0011_remove_question_option5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='applicant_doc',
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicant_date',
            field=models.CharField(default=1, max_length=100, verbose_name='date'),
            preserve_default=False,
        ),
    ]
