# Generated by Django 3.2.9 on 2022-03-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_auto_20220310_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.CharField(default=1, max_length=500, verbose_name='desc'),
            preserve_default=False,
        ),
    ]
