# Generated by Django 3.2.9 on 2022-03-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_experiencein',
            field=models.CharField(max_length=500, verbose_name='experiencein'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_qualificaion',
            field=models.CharField(max_length=500, verbose_name='qualification'),
        ),
    ]
