# Generated by Django 3.2.9 on 2023-03-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0014_auto_20220312_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comapany_pocdis',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_poc',
        ),
    ]
