# Generated by Django 3.2.9 on 2023-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0015_auto_20230304_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='comapany_pocdis',
            field=models.CharField(default=1, max_length=100, verbose_name='posdis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_poc',
            field=models.CharField(default=1, max_length=100, verbose_name='poc_no'),
            preserve_default=False,
        ),
    ]
