# Generated by Django 4.1.7 on 2023-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_auto_20230304_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_mark',
            field=models.CharField(default=1, max_length=100, verbose_name='candidate_mark'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_totalexperienced',
            field=models.FileField(upload_to='images/', verbose_name='candidate_totalexperienced'),
        ),
    ]
