# Generated by Django 4.1.7 on 2023-03-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_candidate_candidate_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='invitation_status',
            field=models.CharField(default=1, max_length=100, verbose_name='status'),
            preserve_default=False,
        ),
    ]
