# Generated by Django 4.1.7 on 2023-03-30 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_applicant_invitation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=200, verbose_name='subject')),
                ('msg', models.CharField(max_length=500, verbose_name='message')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.candidate')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
        ),
    ]
