# Generated by Django 4.1.7 on 2023-03-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_company_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company'),
        ),
        migrations.CreateModel(
            name='user_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=200, verbose_name='sub')),
                ('msg', models.CharField(max_length=500, verbose_name='message')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.candidate')),
            ],
        ),
    ]
