# Generated by Django 4.1.7 on 2023-03-30 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_feedback_company_id_user_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='company_id',
        ),
        migrations.AddField(
            model_name='user_feedback',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company'),
        ),
    ]
