# Generated by Django 4.1.7 on 2023-03-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_remove_feedback_company_id_user_feedback_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub', models.CharField(max_length=200, verbose_name='sub')),
                ('msg', models.CharField(max_length=500, verbose_name='message')),
                ('reply', models.CharField(max_length=500, verbose_name='reply')),
                ('candidate_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.candidate')),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.company')),
            ],
        ),
    ]
