# Generated by Django 3.2.12 on 2023-07-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0022_company_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='candidate_totalexperienced',
            field=models.FileField(upload_to='resumes/', verbose_name='candidate_totalexperienced'),
        ),
    ]
